dist: trusty
sudo: required

language: node_js
node_js:
  - "8"

services:
  - mongodb

cache:
  directories:
     - ./node_modules

before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
  - rm -rf node_modules

install:
  - git clean -fXd
  - npm install -g concurrently
  - npm install
  - meteor npm rebuild
  - npm run meteor-client:bundle
  - npm run api:reset

before_script:
  - "export PATH=$HOME/.meteor:$PATH"

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - npm run test
  - concurrently "npm run start" "npm run api" "sleep 150; npm run e2e" --kill-others --success first
